# fly.toml app configuration file generated for knowledgeforge on 2026-02-12T15:54:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knowledgeforge'
primary_region = 'ams'

[build]

[processes]
  app = '.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[vm]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
